site:
  title: Apache Hop (Incubating)
  url: https://hop.apache.org
  start_page: manual::index.adoc
  keys:
    google_analytics: 'UA-151580460-1'

content:
  sources:
  - url: git@github.com:apache/incubator-hop.git
    branches: 
      - master
    start_path: /docs/hop-user-manual/
  - url: git@github.com:apache/incubator-hop.git
    branches: master
    start_path: /docs/hop-tech-manual/
  - url: git@github.com:apache/incubator-hop.git
    branches: master
    start_path: /docs/hop-dev-manual/
    
ui:
  bundle:
    url: ./antora-ui-hop/build/ui-bundle.zip

urls:
  redirect_facility: disabled

output:
  clean: true
  dir: ./documentation

runtime: 
  fetch: true  

asciidoc:
  extensions:
    - ./extensions/table.js
    - ./extensions/inline-styles.js
